import Link from 'next/link';
import { ArrowRight, BookOpen, CheckCircle2, Clock3, FileText, GraduationCap, LineChart, ShieldCheck, Sparkles, Target, Timer, Trophy } from 'lucide-react';

const Button = ({ href = '/register', children }: { href?: string; children: React.ReactNode }) => <Link href={href} className="inline-flex items-center gap-2 rounded-2xl bg-indigo-600 px-5 py-3.5 text-sm font-black text-white shadow-lg shadow-indigo-600/20 transition hover:-translate-y-0.5 hover:bg-indigo-500">{children}<ArrowRight className="h-4 w-4" /></Link>;

function Hero({ label, title, intro, children }: { label: string; title: string; intro: string; children?: React.ReactNode }) {
  return <section className="overflow-hidden border-b border-indigo-100 bg-[radial-gradient(circle_at_90%_0%,#ddd6fe,transparent_28%),linear-gradient(135deg,#f8fbff,#f6f3ff)] px-5 pb-16 pt-28 dark:border-white/10 dark:bg-[radial-gradient(circle_at_90%_0%,#312e81,transparent_28%),linear-gradient(135deg,#10101d,#17122b)] sm:px-8 lg:pb-20 lg:pt-36"><div className="mx-auto grid max-w-6xl items-center gap-10 lg:grid-cols-[1.05fr_.95fr]"><div><p className="text-xs font-black uppercase tracking-[.18em] text-indigo-600 dark:text-indigo-300">{label}</p><h1 className="mt-5 max-w-3xl font-display text-5xl font-black leading-[.98] tracking-[-.05em] sm:text-6xl">{title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600 dark:text-slate-300">{intro}</p></div>{children}</div></section>;
}

const Panel = ({ children, className = '' }: { children: React.ReactNode; className?: string }) => <div className={`rounded-[2rem] border border-white/80 bg-white/80 p-6 shadow-2xl shadow-indigo-950/10 backdrop-blur dark:border-white/10 dark:bg-white/[.06] ${className}`}>{children}</div>;

export function LearnExperience() {
  const topics = [['Functions', 'Complete', 'bg-emerald-500'], ['Limits & continuity', 'Next up', 'bg-indigo-500'], ['Differentiation', 'Locked', 'bg-slate-300']];
  return <><Hero label="Learn" title="Make the idea click before the questions get hard." intro="Build a dependable maths foundation with short explanations, worked examples, and guided practice in the order that makes sense."><Panel><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-widest text-indigo-600">Learning path</p><h2 className="mt-1 text-2xl font-black">Calculus foundations</h2></div><BookOpen className="h-9 w-9 text-indigo-600" /></div><div className="mt-6 space-y-3">{topics.map(([topic, status, colour]) => <div key={topic} className="flex items-center gap-3 rounded-2xl bg-slate-50 p-4 dark:bg-white/[.06]"><span className={`h-2.5 w-2.5 rounded-full ${colour}`} /><div className="flex-1 text-sm font-bold">{topic}</div><span className="text-xs font-black text-slate-400">{status}</span></div>)}</div><div className="mt-5"><Button>Build my study plan</Button></div></Panel></Hero><section className="px-5 py-16 sm:px-8"><div className="mx-auto max-w-6xl"><p className="text-xs font-black uppercase tracking-[.18em] text-indigo-600">A calmer way to learn</p><div className="mt-6 grid gap-5 md:grid-cols-3">{[['1. Understand','Read the key idea, then see why each step works.'],['2. Follow an example','Unpack a worked solution before attempting it alone.'],['3. Check yourself','Use a short concept check to decide what comes next.']].map(([h,p]) => <article key={h} className="rounded-3xl border border-slate-200 bg-white p-7 dark:border-white/10 dark:bg-white/[.03]"><h2 className="text-xl font-black">{h}</h2><p className="mt-3 leading-7 text-slate-600 dark:text-slate-300">{p}</p></article>)}</div></div></section></>;
}

export function PracticeExperience() {
  return <><Hero label="Practice" title="Practise with a reason, not just a question count." intro="Choose a skill, work through questions at the right level, and turn every flagged or wrong answer into a useful revision task."><Panel><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-amber-100 text-amber-700"><Target /></span><div><p className="text-xs font-black uppercase tracking-widest text-slate-400">Today’s focus</p><h2 className="font-black">Quadratic equations</h2></div></div><div className="mt-7 grid grid-cols-3 gap-3 text-center"><div className="rounded-2xl bg-indigo-50 p-3 dark:bg-indigo-400/10"><b className="block text-xl">12</b><span className="text-xs text-slate-500">Questions</span></div><div className="rounded-2xl bg-emerald-50 p-3 dark:bg-emerald-400/10"><b className="block text-xl">78%</b><span className="text-xs text-slate-500">Accuracy</span></div><div className="rounded-2xl bg-amber-50 p-3 dark:bg-amber-400/10"><b className="block text-xl">3</b><span className="text-xs text-slate-500">To revisit</span></div></div><div className="mt-5"><Button>Start a practice set</Button></div></Panel></Hero><section className="px-5 py-16 sm:px-8"><div className="mx-auto grid max-w-6xl gap-8 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-black uppercase tracking-[.18em] text-indigo-600">My mistakes</p><h2 className="mt-3 font-display text-4xl font-black tracking-tight">Your best revision list is already being made.</h2></div><div className="space-y-3">{[['Sign errors in factorisation','Retry after a worked example'],['Using the quadratic formula','Review today'],['Completing the square','Practise again this week']].map(([h,p]) => <div key={h} className="flex items-center gap-4 rounded-2xl border border-slate-200 bg-white p-5 dark:border-white/10 dark:bg-white/[.03]"><CheckCircle2 className="h-5 w-5 text-indigo-600"/><div><h3 className="font-black">{h}</h3><p className="text-sm text-slate-500">{p}</p></div></div>)}</div></div></section></>;
}

export function TestExperience() {
  return <><Hero label="Test" title="Know your pace before exam day." intro="Use short topic tests and full mock papers to practise focus, time management, and the habit of reviewing what happened after the timer stops."><Panel><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-widest text-indigo-600">Recommended next</p><h2 className="mt-1 text-xl font-black">Limits · Topic test</h2></div><Timer className="h-9 w-9 text-indigo-600" /></div><div className="mt-7 rounded-2xl bg-slate-950 p-5 text-white"><div className="flex justify-between text-sm font-bold"><span>20 questions</span><span>30 min</span></div><div className="mt-4 h-2 rounded-full bg-white/15"><div className="h-full w-2/5 rounded-full bg-emerald-400" /></div><p className="mt-3 text-xs text-slate-300">A focused checkpoint before your next revision session.</p></div><div className="mt-5"><Button href="/resources/mock-tests">Browse mock tests</Button></div></Panel></Hero><section className="px-5 py-16 sm:px-8"><div className="mx-auto max-w-6xl"><h2 className="font-display text-4xl font-black tracking-tight">Tests designed for different moments.</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{[['Quick check','10 questions · 15 min','Find out if a concept is ready to move on.'],['Topic test','20 questions · 30 min','Practise accuracy and method within one chapter.'],['Full mock','Exam duration','Build stamina and a reliable pacing strategy.']].map(([h,meta,p]) => <article key={h} className="rounded-3xl bg-slate-950 p-7 text-white"><span className="text-xs font-black uppercase tracking-widest text-indigo-300">{meta}</span><h3 className="mt-5 text-2xl font-black">{h}</h3><p className="mt-3 leading-7 text-slate-300">{p}</p></article>)}</div></div></section></>;
}

export function AchieveExperience() {
  return <><Hero label="Achieve" title="Progress that tells you what to do next." intro="See more than a score. Track accuracy, time, and confidence by topic so that revision is focused and support arrives at the right moment."><Panel><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-widest text-indigo-600">Weekly mastery</p><h2 className="mt-1 text-3xl font-black">72%</h2></div><LineChart className="h-10 w-10 text-indigo-600" /></div><div className="mt-7 flex h-28 items-end gap-2">{[35,50,42,66,58,78,72].map((n,i) => <div key={i} className="flex-1 rounded-t-lg bg-indigo-500" style={{height:`${n}%`, opacity: i === 6 ? 1 : .35}} />)}</div><p className="mt-4 text-sm font-bold text-emerald-600">↑ 12% from last week</p></Panel></Hero><section className="px-5 py-16 sm:px-8"><div className="mx-auto grid max-w-6xl gap-5 md:grid-cols-3">{[['Strength','Differentiation','Keep the momentum with a timed topic test.'],['Needs attention','Probability','Retry three flagged questions before Friday.'],['This week','4 sessions','A realistic plan is waiting in your dashboard.']].map(([label,h,p]) => <article key={label} className="rounded-3xl border border-slate-200 bg-white p-7 dark:border-white/10 dark:bg-white/[.03]"><p className="text-xs font-black uppercase tracking-widest text-indigo-600">{label}</p><h2 className="mt-4 text-2xl font-black">{h}</h2><p className="mt-3 leading-7 text-slate-600 dark:text-slate-300">{p}</p></article>)}</div><div className="mx-auto mt-10 max-w-6xl"><Button>See my learning dashboard</Button></div></section></>;
}

export function ExamsExperience() {
  const goals = [['CBSE classes 11 & 12','Board-focused concept building, school-aligned practice and revision.'],['NDA / defence','Mathematics practice for consistency, speed and test readiness.'],['CUET entrance','Targeted revision and mock-test preparation for the quantitative section.'],['Foundation mathematics','Build habits and confidence before higher-level study begins.']];
  return <><Hero label="Exams & goals" title="Start with the maths goal in front of you." intro="Mathswiz supports school and entrance preparation with structured lessons, purposeful practice, and feedback that makes each next step clear."><Panel><Sparkles className="h-10 w-10 text-indigo-600"/><h2 className="mt-5 text-2xl font-black">No one-size-fits-all plan.</h2><p className="mt-3 leading-7 text-slate-600 dark:text-slate-300">Choose your goal at enrolment. Your teacher can then guide the right topics, practice and assessments.</p><div className="mt-5"><Button href="/courses">View programmes</Button></div></Panel></Hero><section className="px-5 py-16 sm:px-8"><div className="mx-auto max-w-6xl grid gap-5 md:grid-cols-2">{goals.map(([h,p]) => <article key={h} className="rounded-3xl border border-slate-200 bg-white p-7 dark:border-white/10 dark:bg-white/[.03]"><GraduationCap className="h-7 w-7 text-indigo-600"/><h2 className="mt-6 text-2xl font-black">{h}</h2><p className="mt-3 leading-7 text-slate-600 dark:text-slate-300">{p}</p><Link href="/register" className="mt-6 inline-flex items-center gap-2 font-black text-indigo-600">Ask about this programme <ArrowRight className="h-4 w-4"/></Link></article>)}</div></section></>;
}

export function CoursesExperience() { return <><Hero label="Courses" title="A course should give you a plan—not just more videos." intro="Each Mathswiz programme pairs clear teaching with assignments, timed practice and revision feedback. Enrolment starts with a conversation about your learning goal."><Panel><p className="text-xs font-black uppercase tracking-widest text-indigo-600">Included in every programme</p><div className="mt-5 space-y-4">{['Teacher-guided topic sequence','Practice and mock-test checkpoints','Revision plan based on your attempts'].map(item => <div key={item} className="flex gap-3 font-bold"><CheckCircle2 className="h-5 w-5 shrink-0 text-emerald-500"/>{item}</div>)}</div><div className="mt-6"><Button>Enquire about enrolment</Button></div></Panel></Hero><section className="px-5 py-16 sm:px-8"><div className="mx-auto max-w-6xl grid gap-5 md:grid-cols-2">{[['CBSE Class 11 & 12','Build board confidence through concepts, examples, chapter practice and regular feedback.'],['NDA mathematics','Develop speed, accuracy and dependable test habits for the mathematics paper.'],['CUET quantitative preparation','Revise core skills, practise exam-style questions and learn how to use time wisely.'],['NEET / medical foundation','Strengthen the mathematical confidence and problem-solving habits useful alongside medical entrance preparation.']].map(([h,p]) => <article key={h} className="rounded-3xl border border-slate-200 bg-white p-7 dark:border-white/10 dark:bg-white/[.03]"><h2 className="text-2xl font-black">{h}</h2><p className="mt-3 leading-7 text-slate-600 dark:text-slate-300">{p}</p><Link href="/register" className="mt-6 inline-flex items-center gap-2 text-sm font-black text-indigo-600">Talk to us about this course <ArrowRight className="h-4 w-4" /></Link></article>)}</div></section></> }

export function MockTestsExperience() { return <><Hero label="Mock tests" title="Make the timer familiar before it matters." intro="Mock tests give students a safe way to practise stamina, pacing and calm decision-making—followed by a report that turns the attempt into a revision plan."><Panel><Clock3 className="h-10 w-10 text-indigo-600"/><h2 className="mt-5 text-2xl font-black">After every test</h2><ul className="mt-5 space-y-3 text-sm font-bold text-slate-600 dark:text-slate-300"><li>• Review every incorrect and flagged question</li><li>• See time spent by topic</li><li>• Add weak skills to your next practice plan</li></ul><div className="mt-6"><Button>Ask about mock access</Button></div></Panel></Hero><section className="px-5 py-16 sm:px-8"><div className="mx-auto max-w-6xl"><div className="rounded-[2rem] border border-slate-200 bg-white p-7 dark:border-white/10 dark:bg-white/[.03]"><p className="text-xs font-black uppercase tracking-widest text-indigo-600">How it works</p><div className="mt-7 grid gap-6 md:grid-cols-3">{[['Choose','Start with a chapter check or prepare for a full paper.'],['Attempt','Work in one sitting with a clear timer and no distractions.'],['Analyse','Use the report to plan the questions and concepts to revisit.']].map(([h,p], i) => <div key={h}><span className="text-4xl font-black text-indigo-100">0{i+1}</span><h2 className="mt-3 text-xl font-black">{h}</h2><p className="mt-2 leading-7 text-slate-600 dark:text-slate-300">{p}</p></div>)}</div></div></div></section></> }

export function PreviousPapersExperience() { return <><Hero label="Previous year papers" title="Use past papers to practise decisions, not memorise patterns." intro="A previous paper is most useful when it is treated like a real attempt: timed, reviewed carefully, and turned into a short revision plan."><Panel><FileText className="h-10 w-10 text-indigo-600"/><h2 className="mt-5 text-2xl font-black">A better paper review</h2><ol className="mt-5 space-y-3 text-sm font-bold"><li>1. Mark questions that slowed you down.</li><li>2. Separate a concept gap from a careless error.</li><li>3. Retry the right questions after revision.</li></ol></Panel></Hero><section className="px-5 py-16 sm:px-8"><div className="mx-auto max-w-6xl"><h2 className="font-display text-4xl font-black tracking-tight">What to bring to each paper.</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{[['A timer','Practise one uninterrupted sitting when you can.'],['A review note','Capture why an answer went wrong, not just the answer.'],['A next action','Schedule a retry after the concept is fresh again.']].map(([h,p]) => <article key={h} className="rounded-3xl bg-indigo-600 p-7 text-white"><h3 className="text-xl font-black">{h}</h3><p className="mt-3 leading-7 text-indigo-100">{p}</p></article>)}</div><div className="mt-9"><Button>Enquire about paper practice</Button></div></div></section></> }

export function SuccessExperience() { const stories = [['Aarav Sharma','Class 12 · CBSE','“The practice feedback showed me exactly what to revise. Maths stopped feeling like guesswork.”'],['Priya Patel','Class 11 · Foundation','“The lessons are simple, the questions build up properly, and I can finally see my progress.”'],['Rohan Verma','NDA aspirant','“Timed practice helped me stay calm under pressure. I now know where my marks are coming from.”']]; return <><Hero label="Student stories" title="Confidence grows one small win at a time." intro="These stories are about more than marks: students finding a routine, understanding what went wrong, and staying with mathematics long enough to improve."><Panel><Trophy className="h-10 w-10 text-amber-500"/><p className="mt-5 text-xl font-black">The pattern is consistent.</p><p className="mt-3 leading-7 text-slate-600 dark:text-slate-300">Clear teaching + thoughtful practice + feedback that leads somewhere.</p><div className="mt-6"><Button>Start your own plan</Button></div></Panel></Hero><section className="px-5 py-16 sm:px-8"><div className="mx-auto max-w-6xl grid gap-5 md:grid-cols-3">{stories.map(([name,detail,quote]) => <figure key={name} className="rounded-[2rem] border border-slate-200 bg-white p-7 dark:border-white/10 dark:bg-white/[.03]"><blockquote className="text-lg font-bold leading-8">{quote}</blockquote><figcaption className="mt-8"><p className="font-black">{name}</p><p className="text-sm text-slate-500">{detail}</p></figcaption></figure>)}</div></section></> }

export function PrivacyExperience() { return <><Hero label="Privacy" title="Learning data should be handled with care." intro="This summary explains the information Mathswiz uses to operate the learning platform and how students, parents and teachers can ask for support."><Panel><ShieldCheck className="h-10 w-10 text-emerald-600"/><p className="mt-5 text-xl font-black">We do not sell personal learning data.</p><p className="mt-3 leading-7 text-slate-600 dark:text-slate-300">Information is used to provide accounts, learning progress, teacher support and relevant communication.</p></Panel></Hero><section className="px-5 py-16 sm:px-8"><div className="mx-auto max-w-4xl space-y-5">{[['Information we use','Account contact details, enrolment context, learning activity, test attempts and progress records needed to provide the service.'],['Why we use it','To operate the platform, personalise practice, show progress, help teachers support learners, and respond to account requests.'],['Who can see it','Students see their own learning. Authorised teachers and school administrators see information needed to support their classes. Parents receive the updates made available for their child.'],['Your choices','For account, correction, access or deletion questions, contact Sindhu’s Mathswiz Classes at sindhu.mathswiz@gmail.com.']].map(([h,p]) => <article key={h} className="rounded-3xl border border-slate-200 bg-white p-7 dark:border-white/10 dark:bg-white/[.03]"><h2 className="text-xl font-black">{h}</h2><p className="mt-3 leading-7 text-slate-600 dark:text-slate-300">{p}</p></article>)}</div></section></> }
