import { getServerSession } from "next-auth";
import { NextResponse } from "next/server";
import prisma from "@/lib/prisma";
import { authOptions } from "@/lib/auth";

// Load Balancer Helper
const fetchFromBalancedLLM = async (systemPrompt: string, userPrompt: string) => {
    const groqKeys = (process.env.GROQ_API_KEYS || "").split(",").filter(k => k.trim() !== "");
    const geminiKeys = (process.env.GEMINI_API_KEYS || "").split(",").filter(k => k.trim() !== "");
    const availableProviders = [];
    if (groqKeys.length > 0) availableProviders.push("GROQ");
    if (geminiKeys.length > 0) availableProviders.push("GEMINI");
    if (availableProviders.length === 0) throw new Error("No API keys configured.");

    const provider = availableProviders[Math.floor(Math.random() * availableProviders.length)];

    if (provider === "GROQ") {
        const key = groqKeys[Math.floor(Math.random() * groqKeys.length)];
        const res = await fetch("https://api.groq.com/openai/v1/chat/completions", {
            method: "POST",
            headers: { "Authorization": `Bearer ${key.trim()}`, "Content-Type": "application/json" },
            body: JSON.stringify({
                // llama-3.1-8b-instant was retired by Groq (404 model_not_found);
                // openai/gpt-oss-120b is confirmed working (see lib/llm.ts).
                model: "openai/gpt-oss-120b",
                messages: [{ role: "system", content: systemPrompt }, { role: "user", content: userPrompt }],
                response_format: { type: "json_object" }
            })
        });
        if (!res.ok) throw new Error("Groq API failed");
        const data = await res.json();
        return data.choices[0].message.content;
    } else {
        const key = geminiKeys[Math.floor(Math.random() * geminiKeys.length)];
        // gemini-1.5-flash and gemini-2.0-flash were both retired by Google;
        // gemini-3.5-flash / gemini-2.5-flash are confirmed working (lib/llm.ts).
        let res: Response | null = null;
        for (const model of ["gemini-3.6-flash", "gemini-3.5-flash"]) {
            res = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${key.trim()}`, {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    systemInstruction: { parts: [{ text: systemPrompt }] },
                    contents: [{ parts: [{ text: userPrompt }] }],
                    generationConfig: { responseMimeType: "application/json" }
                })
            });
            if (res.ok) break;
        }
        if (!res || !res.ok) throw new Error("Gemini API failed");
        const data = await res.json();
        return data.candidates[0].content.parts[0].text;
    }
};

export async function POST(req: Request) {
    try {
        const session = await getServerSession(authOptions);
        if (!session?.user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

        const isPremium = (session.user as any)?.subscription === "PREMIUM";
        if (!isPremium) return NextResponse.json({ error: "Worksheet Solver is a Premium Feature." }, { status: 403 });

        const formData = await req.formData();
        const image = formData.get('image') as File;
        if (!image) return NextResponse.json({ error: "Image required" }, { status: 400 });

        // 1. Mathpix OCR (Full Page)
        const buffer = Buffer.from(await image.arrayBuffer());
        const base64 = buffer.toString('base64');
        
        const mathpixRes = await fetch("https://api.mathpix.com/v3/text", {
            method: "POST",
            headers: {
                "app_id": process.env.MATHPIX_APP_ID!,
                "app_key": process.env.MATHPIX_APP_KEY!,
                "Content-Type": "application/json"
            },
            body: JSON.stringify({ src: `data:${image.type};base64,${base64}`, formats: ["text"] })
        });
        const mathpixData = await mathpixRes.json();
        const rawText = mathpixData.text || "";

        if (!rawText.trim()) throw new Error("No mathematical content found in the worksheet.");

        // 2. LLM Splitting & Structuring
        const systemPrompt = `You are a mathematical data engineer. I will give you OCR text from a physical school worksheet.
        Your task is to split this text into individual, unique digital questions.
        
        ### OUTPUT FORMAT:
        Return a JSON object with a "questions" array.
        Each object in the array MUST have:
        - "content": The question text using LaTeX ($ for inline, $$ for block).
        - "options": Array of 4 strings (if it looks like an MCQ) or empty array [] if not.
        - "correctAnswer": The correct answer if mentioned, or a placeholder like "A".
        - "explanation": A detailed LaTeX solution generated by you.
        - "topic": The broad topic (e.g., "Calculus").
        - "difficulty": "EASY", "MEDIUM", or "HARD".
        
        ONLY output VALID JSON. No markdown blocks.`;

        const rawJson = await fetchFromBalancedLLM(systemPrompt, `Worksheet Content:\n${rawText}`);
        
        let parsed;
        try {
            const cleaned = rawJson.replace(/```json/gi, "").replace(/```/g, "").trim();
            parsed = JSON.parse(cleaned);
        } catch (e) { throw new Error("AI failed to structure the worksheet data."); }

        const questions = parsed.questions || [];

        // 3. Save Questions with "Worksheet-Solve" tag (Auto-Approved for the student)
        const savedQuestions = [];
        for (const q of questions) {
            try {
                const saved = await prisma.question.create({
                    data: {
                        content: q.content,
                        options: q.options || [],
                        correctAnswer: q.correctAnswer || "",
                        explanation: q.explanation || "",
                        topic: q.topic || "General",
                        difficulty: q.difficulty || "MEDIUM",
                        type: q.options?.length > 0 ? "SINGLE_CHOICE" : "SUBJECTIVE",
                        status: "APPROVED",
                        tags: ["Worksheet-Import", `Import-${session.user.email}`],
                        createdById: (session.user as any).id || "admin"
                    }
                });
                savedQuestions.push(saved);
            } catch (dbErr) { console.error("Failed to save worksheet question", dbErr); }
        }

        return NextResponse.json({ success: true, questions: savedQuestions });

    } catch (error: any) {
        console.error("Worksheet Solver Error:", error);
        return NextResponse.json({ error: error.message }, { status: 500 });
    }
}

